// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    Login: typeof import('./src/components/Login.vue')['default']
    NotebookList: typeof import('./src/components/NotebookList.vue')['default']
    NoteDetail: typeof import('./src/components/NoteDetail.vue')['default']
    NoteSidebar: typeof import('./src/components/NoteSidebar.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TrashDetail: typeof import('./src/components/TrashDetail.vue')['default']
  }
}

export { }
